### ISSUE TITLE
compile error on centos7

### ISSUE THREAD

**Issue by addriumruss** [google/earthenterprise#1076]
environment: centos7 x64, gcc4.8.5
got this error:

[root@izbp1isnabg70w8m1aleriz earth_enterprise]# scons -j8 release=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 release=1 third_party
scons: Reading SConscript files ...
Checking for C library gtest... (cached) yes
Checking for C header file libpng12/png.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
set -x && cd /home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4 && env CFLAGS="" CXXFLAGS="" PATH="/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin:/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin:/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin:/bin:/usr/bin" make CSTAR_FLAGS="-O2 -Wall -fPIC -fexceptions" && touch /home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/.build
+ cd /home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4
+ env CFLAGS= CXXFLAGS= PATH=/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin:/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin:/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/bin:/bin:/usr/bin make 'CSTAR_FLAGS=-O2 -Wall -fPIC -fexceptions'
/bin/perl utils/svn_repo_revision.pl
Can't fetch local revision (neither .svn nor .git found)
Not updating existing rev file at 16009
for s in liblwgeom libpgcommon postgis regress raster topology loader utils doc extensions; do \
	echo "---- Making all in ${s}"; \
	make -C ${s} all || exit 1; \
done;
---- Making all in liblwgeom
make[1]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/liblwgeom'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/liblwgeom'
---- Making all in libpgcommon
make[1]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/libpgcommon'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/libpgcommon'
---- Making all in postgis
make[1]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/postgis'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/postgis'
---- Making all in regress
make[1]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/regress'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/regress'
---- Making all in raster
make[1]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster'
make -C rt_core
make[2]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/rt_core'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/rt_core'
make -C rt_pg
make[2]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/rt_pg'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/rt_pg'
make -C loader
make[2]: Entering directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/loader'
/bin/sh ../../libtool --mode=link /home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc -O2  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom  -I/opt/google/include -I/usr/include   ../rt_core/librtcore.a raster2pgsql.o -lstdc++ ../../liblwgeom/liblwgeom.la -L/opt/google/lib -lgdal  -L/usr/lib64 -lgeos_c  -lc -lm -o raster2pgsql
libtool: link: /home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc -O2 -fPIC -DPIC -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/opt/google/include -I/usr/include raster2pgsql.o -o .libs/raster2pgsql  ../rt_core/librtcore.a ../../liblwgeom/.libs/liblwgeom.so -L/usr/lib64 -lstdc++ -lproj -L/opt/google/lib /usr/lib64/libgdal.so -L/usr/local/lib /usr/local/lib/libgeos_c.so /usr/local/lib/libgeos.so -lexpat -lxerces-c -logdi -lgif -ljpeg -ltiff -lpng -lpthread -lrt -lpcre -lcurl -lxml2 -lz -ldl -lgeos_c -lc -lm -Wl,-rpath -Wl,/opt/google/lib -Wl,-rpath -Wl,/usr/local/lib
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_addpoint'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_compute'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_init'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_init'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_direct'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_inverse'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/home/russ/gis/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.4/raster'
make: *** [all] Error 1
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/postgis/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.

any solution?

**Comment by tst-lsavoie** [comment]
That looks like a missing library. Have you installed all the libraries listed in https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md?

**Comment by tst-lsavoie** [comment]
Since there hasn't been much movement on this recently, I'm going to close the issue. Feel free to reopen it if you're still having trouble.

**Comment by marvins** [comment]
I just noticed this myself.  I have followed the build and compilation instructions to the letter.   

Here is my compile command

    scons -j8 release=1 build

Here is the point of failure. 

`   .... skipping for brevity ...
make[2]: Entering directory `/home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9/raster/rt_pg'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9/raster/rt_pg'
make -C loader
make[2]: Entering directory `/home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9/raster/loader'
/bin/sh ../../libtool --mode=link /home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc -O2  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom  -I/opt/google/include -I/usr/include   ../rt_core/librtcore.a raster2pgsql.o -lstdc++ ../../liblwgeom/liblwgeom.la -L/opt/google/lib -lgdal  -L/usr/lib64 -lgeos_c  -lc -lm -o raster2pgsql
libtool: link: /home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/bin/gcc -O2 -fPIC -DPIC -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/opt/google/include -I/usr/include raster2pgsql.o -o .libs/raster2pgsql  ../rt_core/librtcore.a -lstdc++ ../../liblwgeom/.libs/liblwgeom.so -L/opt/google/lib -lgdal -L/usr/lib64 -lgeos_c -lc -lm -Wl,-rpath -Wl,/opt/google/lib
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_addpoint'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_compute'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_init'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_polygon_init'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_direct'
../../liblwgeom/.libs/liblwgeom.so: undefined reference to `geod_inverse'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/home/msmith/Projects/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9/raster'
make: *** [all] Error 1
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/postgis/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.`    

I realized it was postgis, then navigated to that specific project and got the same result. 

`cd src/NATIVE-REL-x86_64/third_party/postgis/postgis-2.3.9
make`

**Comment by tst-lsavoie** [comment]
We build on CentOS regularly and haven't run into this. I'm firing up a fresh VM to test it out, but in the meantime is it possible that an error happened in one of the steps in the build instructions? It looks like some dependency wasn't installed correctly.

**Comment by tst-lsavoie** [comment]
My CentOS 7 build passed. Here's a few things that might cause problems:
- On [BUILD.md](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md) step 1 there are links to specific build instructions for different platforms. Be sure to follow the RedHat CentOS link and follow the steps there before building.
- On the [CentOS-specific instructions](https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD_RHEL_CentOS.md) you need to follow all the steps labeled either CentOS 7, EL 7, or that have no label for a specific operating system. If the step has no label, it applies to all OSes.

If neither of those fixes your problem, it would help if you could give us more detailed information about your environment (exact CentOS version, Open GEE commit you're building, etc).
