### ISSUE TITLE
Contact eMail cannot be reached.

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [google/earthenterprise#1128]
The eMail gee-oss@googlegroups.com given as a contact on opengee.org returns a Delivery Status Notification (Failure) when written to.

**Comment by tst-ccamp** [comment]
The email address appears to still be valid, as the group is there. https://groups.google.com/forum/#!aboutgroup/gee-oss

I'm not sure why email may not be working. Maybe you have to be a member of the group in order to send email. I'll look into it. Maybe we need a different type of email alias. In the mean time, feel free to post your message here: https://groups.google.com/forum/#!forum/google-earth-enterprise

**Comment by tst-lsavoie** [comment]
As far as we can tell everything is working correctly, so I'm going to close this ticket. If you still have problems feel free to re-open it or create a new ticket.
