### ISSUE TITLE
the error show  on save Imagery

### ISSUE THREAD

**Issue by wangjunqin** [google/earthenterprise#137]
Build an Imagery Resource as the steps,it occur error while save the imagery,the error info show that" unable to save: Resources/Imagery/SFBayAreaLanSat_20021010.kiasset /opt/google/share/tutorials/fusion/imagery/usgsLanSat.jp2 doesn't reside on a known volume."

**Comment by tst-ccamp** [comment]
Hey @wangjunqin, I think you've uncovered a couple different issues here. First, the Fusion UI isn't supposed to allow you to select .jp2 files because JPEG 2000 files aren't supported in the open source version. We have another ticket to look into adding that support that later. Can you create this resource again and instead choose the .tif version of the file and let us know if you still get the same error?

Second, you may also need to configure /opt/google/share/tutorials/fusion as a valid source volume. This page in the documentation should help with that.
http://www.opengee.org/geedocs/answer/3481499.html
