### ISSUE TITLE
How can I preview my published GEE database in browser?

### ISSUE THREAD

**Issue by carlblack1987** [google/earthenterprise#1407]
With the document, I define and publish my first database in Fusion and then I publish it in Admin Console.
However, the document tells me that I should use GEE client to view this database. 
But I found that in Admin Console database tab, when the database gets selected a preview button comes out. I click the preview button and a new browser tab is open. 
Then an alert dialog comes out to tell me "ALERT! The Google Earth Plugin failed to load!"
Does this means that I can view my database in browser? If I could, where shall I get this plugin?

**Comment by tst-ccamp** [comment]
Hi @carlblack1987, the in-browser plugin hasn't been supported or available for download from Google since 2015. We can't offer it for download or offer support for it. You will need the Google Earth Enterprise Client to view the database. You can download that here: https://github.com/google/earthenterprise/wiki/Google-Earth-Enterprise-Client-(EC)
