### ISSUE TITLE
Vector resource build fails unless source files have write access

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#16]
When trying to build a vector resource, the file must have write access for gefusionuser. If not, the build will fail with a “permission denied” error. Earlier versions of fusion did not have this issue.

**Comment by asmitaw** [comment]
first of all, the error details :

Fusion Notice:	Begin source validation phase.
Fusion Notice:	Opening source /opt/google/share/tutorials/fusion/Vector/california_roads_line.shp
Warning 4: Failed to open /opt/google/share/tutorials/fusion/Vector/california_roads_line.shp, Permission denied.

file permissions 
-rw-r--r-- 1 root   root     380788 May 31 16:57 california_roads_line.shp

the issue is that when we open this file, we open as write mode.

**Comment by asmitaw** [comment]
inspecting this code:

https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/autoingest/plugins.src/VectorProduct.src#L138

**Comment by andreisel** [comment]
@asmitaw Should be somewhere here: [gstSource::Open()](https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/gst/gstSource.cpp#L63). Used from here: [gevectorimport.cpp](https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/tools/gevectorimport.cpp#L530)

**Comment by asmitaw** [comment]
thanks Andrei.
I noticed that same permissions work on the csv file whereas for shape file they dont. 

e.g. 
-rw-r--r-- 1 root root  4273543 Jun  6 16:46 UsPopPlaces.csv
 -rw-r--r-- 1 root root   960420 Jun  6 16:46 california_hydro_line.shp

Ideally, the shapefile format is implemented correct with only "read" permissions https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/gst/gstSHPFormat.cpp#L41
see,  if (!(_fpSHP = fopen(name(), "r"))  ...

However something has changed that SHP is not hitting this code, I believe something might have changed because of the GDAL update as reports are that it did not happen in 5.1.2

**Comment by asmitaw** [comment]
we should use Bitwise OR instead of logical to have the effect of GDAL_OF_VECTOR GDAL_OF_READONLY 

https://github.com/OSGeo/gdal/blob/77544764f51420e42468641fc3d5a087f8ea6d8f/gdal/gnm/gnm_tut.dox#L150

So, the fix is to fix the operator in the OGRFormat::OpenFile

**Comment by asmitaw** [comment]
I tried the fix and it works, will send the commit request soon.
