### ISSUE TITLE
Publish module fails to run due to missing dependency in RHEL 7

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#17]
After doing a build and deploy using Andrei’s script, the Apache Publish module does not work. (So far I have only seen this on RHEL 7) This error in the GEE error log (/opt/google/gehttpd/logs/error_log):
```
[Thu Mar 23 20:04:02 2017] [error] [client 10.240.0.3]   File "/opt/google/gehttpd/wsgi-bin/serve/publish/publish_app.wsgi", line 1, in <module>
...
[Thu Mar 23 20:04:02 2017] [error] [client 10.240.0.3]     import psycopg2  # NO LINT. third party package should be before own ones.
[Thu Mar 23 20:04:02 2017] [error] [client 10.240.0.3] ImportError: No module named psycopg2
```

**Comment by avnishb** [comment]
This is a known issue in the latest build.  Also occurs in Ubuntu.  We are investigating.
@andreisel @asmitaw @dattapm

**Comment by andreisel** [comment]
It is different issue, I fixed this on Ubuntu build by adding into mod_wsgi_ge.conf (third_party/mod_wsgi/conf.d/mod_wsgi-ge.conf) a path to site-packages:
/opt/google/gepython/Python-2.7.6/lib/python2.7/site-packages

I believe that problem here is that RHEL 7 may have different python version, so that the path referenced in mod_wsgi_ge.conf is incorrect.

Seems there are two options:
A) bundle python and related libs, so we can use static path in mod_wsgi_ge.conf. 
B) have template with placeholders for mod_wsgi_ge.conf and generate final mod_wsgi_ge.conf when deploying Server.

For now, we can just revert bundling of python. Need to only update third_party/SConscript, and third_party/mod_wsgi/conf.d/mod_wsgi-ge.conf

**Comment by tst-lsavoie** [comment]
@andreisel is this issue related to #36?

**Comment by andreisel** [comment]
No it is not related to #36. In OSS version, we unbundled bunch of 3rd party libs and use python from system.
I believe we just need to update https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/third_party/mod_wsgi/conf.d/mod_wsgi-ge.conf. Should be generated when installing/deploying to use system-python version in python-path.
Suggestion can be verified on RHEL 7 by updating "python-path=/opt/google/gepython/Python-2.7.6/lib/python2.7/site-packages" in /opt/google/gehttpd/conf.d/mod_wsgi-ge.conf to use RHEL python versions. After building and deploying on RHEL 7, please check what path is to site-packages dir. in /opt/google/gepython/, and put that path to /opt/google/gehttpd/conf.d/mod_wsgi-ge.conf. Then restart geserver daemon and verify push/publish.

**Comment by tst-lsavoie** [comment]
Looks like simply changing "/opt/google/gepython/Python-2.7.6/lib/python2.7/site-packages" to "/opt/google/gepython/Python-2.7.5/lib/python2.7/site-packages" (note the python version number) does the trick.

**Comment by tst-lsavoie** [comment]
It seems I don't have permission to assign this to myself, but I am working this issue.
