### ISSUE TITLE
install instructions are not clear

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#205]
(Mandatory) Create the install package

cd earthenterprise/earth_enterprise
scons -j8 release=1 stage_install

expected :
cd earthenterprise/earth_enterprise/src
what is "stage_install" mean ?  - It would be good to have an explanation for the same

**Comment by asmitaw** [comment]
install wiki -  https://github.com/google/earthenterprise/wiki/Install-Fusion-or-Earth-Server

**Comment by bradh** [comment]
I believe that this is intended (i.e. correct as written) after merging of https://github.com/google/earthenterprise/commit/8a2b5a67ef65b15c4d20d9ada2333bd82ca64d23

@tst-lsavoie can probably clarify.

**Comment by tst-ccamp** [comment]
Yes, @asmitaw, this change is intentional. It simplifies the build instructions by eliminating constant directory changes. The easiest way to do this was to bring everything to the top level scons file. The build steps were reduced from 2 steps to 1. The install steps were reduced from 3 steps to 1. See #131.

We can add add more explanation as to what stage_install means. We actually discussed this a good bit. We couldn't really come up with a good word to describe what scons is doing. It's not actually installing because there is another step after the scons target to run the install scripts. We finally settled on the less than perfect "stage_install". However, the "install" target still works.
