### ISSUE TITLE
Not able to cut the globe

### ISSUE THREAD

**Issue by gautamp86** [google/earthenterprise#241]
I have installed fusion and earth server on ubuntu machine. Portable is installed on another machine (windows).
Getting following error while cutting the globe from windows machine.
![error](https://user-images.githubusercontent.com/28753606/27168690-7272e46e-51c4-11e7-9be0-5d7935ebf4cd.PNG)

**Comment by asmitaw** [comment]
can you expand that error  (left arrow) and paste the message here. its hard to see for me.

**Comment by gautamp86** [comment]
![snapshot_error](https://user-images.githubusercontent.com/28753606/27172726-d0b98ff0-51d3-11e7-90ef-83a0b9be9f29.PNG)

**Comment by asmitaw** [comment]
so that is 3D globe you are trying to cut?

**Comment by gautamp86** [comment]
yes, but not having world imagery but having specific area image

**Comment by asmitaw** [comment]
I am not a portable expert, your browser is failing to load the 3D plugin so unless you have the plugin , try 2D globe first is my suggestion ( i.e.  .glm	Portable 2D map )

**Comment by gautamp86** [comment]
while cutting the map also i am getting same error
![maperror](https://user-images.githubusercontent.com/28753606/27173455-67faa802-51d6-11e7-80bf-240f4a489d50.PNG)

**Comment by asmitaw** [comment]
can you inspect the logs at /opt/google/gehttpd/logs/access_log and 
/opt/google/gehttpd/logs/error_log ?

**Comment by asmitaw** [comment]
I mean the geserver logs that are serving the globe

**Comment by asmitaw** [comment]
just see if any error reported in the logs 
tail -10  /opt/google/gehttpd/logs/error_log 
tail -10  /opt/google/gehttpd/logs/access_log

**Comment by gautamp86** [comment]
![error_logs](https://user-images.githubusercontent.com/28753606/27175617-552daace-51dd-11e7-873d-1c7f30502619.PNG)

**Comment by protodonuts** [comment]
Apperantly something wrong here

https://github.com/google/earthenterprise/blob/762190bd1a88dcf8e94959d201801b672bc7ee1d/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/globe_cutter_app.py#L308

pointed out by github's syntax highlighting.

**Comment by bradh** [comment]
Certainly that newline in the middle of the string isn't a good sign...

**Comment by asmitaw** [comment]
yeah, take out that copyright text and rebuild

**Comment by bradh** [comment]
@gautamp86 I think that guidance from @asmitaw is for you. Can you retry with that fixed?

**Comment by asmitaw** [comment]
@gautamp86 please remove the copyright lines in below place and try build and reinstall the geserver and try to cut:
https://github.com/google/earthenterprise/blob/7dbd0ded23620ffdbd73f21f3a4d3cf9ed8d807e/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/globe_cutter_app.py#L308

I wont be able to test myself right now. so if it works for you, I can do a pull request later today( or @bradh @protodonuts feel free to take it.

**Comment by gautamp86** [comment]
ok. sure.

**Comment by protodonuts** [comment]
Should just update /opt/google/gehttpd/cgi-bin/globe_cutter_app.py and see if things go right.

**Comment by gautamp86** [comment]
@protodonuts  - I removed the highlighted line and restarted the server
![removed](https://user-images.githubusercontent.com/28753606/27177405-e7378c72-51e3-11e7-86d6-33be73b68594.PNG)
After that I am getting following error:
![error](https://user-images.githubusercontent.com/28753606/27177593-86e02cca-51e4-11e7-9146-4fcbccb26663.PNG)
![errorlog](https://user-images.githubusercontent.com/28753606/27177623-9496589e-51e4-11e7-8c22-a7139009bc26.PNG)

**Comment by bradh** [comment]
@gautamp86 Looks like missing dependencies. Suggest installing `python2.7-psycopg2` module and seeing how that goes.

**Comment by gautamp86** [comment]
@bradh - After installing python2.7-psycopg2 module, I am getting following error:
![error](https://user-images.githubusercontent.com/28753606/27179301-969bf4ee-51eb-11e7-9e33-1411d1f0bc68.PNG)

**Comment by gautamp86** [comment]
Will the following highlighted line affect the functionality?
![geserver_restart](https://user-images.githubusercontent.com/28753606/27179730-781f53ec-51ed-11e7-81f7-f8ffee550816.PNG)

**Comment by bradh** [comment]
Doubt that is the problem. More likely some problem with bad resolution of what "utils.py" is actually meant to be.

**Comment by bradh** [comment]
I added python2.7-psycopg2 to the wiki and will propose the PR. Someone else will need to test it though...

**Comment by andreisel** [comment]
GEE has a bundled version of psycopg2 - it is being built and deployed to /opt/googlegepython/Python-.../site-packages/
For wsgi-modules (GEE Server) all paths are configured in [mod_wsgi-ge.conf.in](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/third_party/mod_wsgi/conf.d/mod_wsgi-ge.conf.in)

For cutter modules (located in cgi-bin), likely need to add to search paths next directories:
/opt/google/gepython/Python-@PYTHON_VERSION@/lib/python@PYTHON_MAJOR_VERSION@/site-packages
/opt/google/gehttpd/wsgi-bin

**Comment by tst-awankhede** [comment]
@gautamp86 : please copy the error messages vs screenshots in the bugs. That way we can search the issues from errors or logs etc.

**Comment by gautamp86** [comment]
@tst-awankhede - Sure

**Comment by tst-awankhede** [comment]
@gautamp86, Were you able to fix the issue after adding the search paths for cutter as suggested by @andreisel ?

**Comment by gautamp86** [comment]
@andreisel - Sorry, but kindly help me to understand that in which file do i need to change? because i can see that the file "mod_wsgi-ge.conf.in" contains same entries 5 times.

**Comment by andreisel** [comment]
@gautamp86, @tst-ccamp 

1) you don't need to install psycopg2. It is being build and deployed with GEE into /opt/google/gepython/Python-@PYTHON_VERSION@/lib/python@PYTHON_MAJOR_VERSION@/site-packages

Since we switched to system python, cgi-bin python modules using system python can't find psycopg2 located in /opt/google/gepython/....
The path above needs to be added to search paths, so system python can find modules (psycopg2) located there. For wsgi-app, I pointed you to solution (mod_wsgi-ge.conf.in) where you can find path that you need.
For cgi-bin modules, need to find solution how better to do this. Temp. solution could be inserting path into sys.paths like [here](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/common/postgres_manager_wrap.py#L28)

@tst-ccamp Chris, one time we thought about moving all cgi-bin modules under wsgi-bin, and making them wsgi-apps, but I believe it will take a time.

2) On your screenshot (see comment "After installing python2.7-psycopg2 module, I am getting following error"), you can see that /opt/google/gehttpd/cgi-bin/glober_cutter_app.py fails on import postgres_manager_wrap because can't find [utils.GetPostgresPortNumber()](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/server/wsgi/common/postgres_properties.py#L26) .

Please see the temp. solution  in [postgres_manager_wrap.py](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/common/postgres_manager_wrap.py#L28) which allow to use postgres_manager.py from wsgi-bin.
I believe the issue here is that "from common import utils" in [postgres_properties.py](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/server/wsgi/common/postgres_properties.py#L18) actually imports the utils-module from [cgi-bin/common](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/common/utils.py), so couldn't find function utils.GetPostgresPortNumber().

**Comment by bradh** [comment]
Should we just switch to making it a system dependency? I think it would be better to use system packages where possible, and this seems like an easy case.

**Comment by andreisel** [comment]
+ @tst-ccamp, @tst-ppenev 
@bradh,  
You are right. It was the goal -  unbundle as much as possible third-party packages. Most of the third-party packages were unbundled.
AFAIR unbundling of the psycopg2 will require to unbundle postgresql, postgis, etc(?).
Please look for comments in the [third_party/SConscript](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/third_party/SConscript).

**Comment by bradh** [comment]
@andreisel There should not be tight coupling between the psycopg2 client and the postgres/postgis servers. Do you know of a specific problem that we can test against to see if it occurs on current distro releases?

**Comment by andreisel** [comment]
@bradh I don't remember exactly, and there was no thorough investigation of the issue. Please, feel free to give a try by commenting psycopg2 in [third_party/SConscript](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/third_party/SConscript)

**Comment by tst-ahernandez** [comment]
@gautamp86 Are there any new updates on this issue? If not I will close it tomorrow.

**Comment by tst-awankhede** [comment]
list  apt-get install python-psycopg2 as the prerequisite of cutter in the portable install documentation

**Comment by asmitaw** [comment]
@gautamp86 we provided a fix, please pull latest master branch to try it.

**Comment by tst-awankhede** [comment]
@gautamp86 we provided a fix, please pull latest master branch to try it.
