### ISSUE TITLE
install GEE on Localhost

### ISSUE THREAD

**Issue by swazm-zz** [google/earthenterprise#246]
when I try to install Fusion with this command

**sudo ./install_fusion.sh**

i have this message 

****Welcome to the Google Earth Enterprise Fusion 5.1.3 installer.

The hostname of this machine does not match the fully-qualified hostname.
 requires that they match for local publishing to function properly.
Exiting the installer.  If you wish to continue, re-run this command with the -hnmf 'Hostname Mismatch Override' flag.****

how to configure my hostname
do i need to install and configure **postgres**, **postgis**, **apache server**,  before installing fusion and GE Server ?

thanks

**Comment by asmitaw** [comment]
Are there custom hostnames configured on this machine ? Host or network files changed ? What does a "ping localhost" conmand prints?

**Comment by asmitaw** [comment]
127.0.0.1	localhost - does this entry exists in your etc/hosts ? what does the localhost correspond to?
your Qs:
do i need to install and configure postgres, postgis, apache server, before installing fusion and GE Server ? - Ans: No , there is no such requirement

**Comment by swazm-zz** [comment]
I do not have a custom hostnames.
 
 in my  etc/hosts : 
**127.0.0.1  localhost** 
127.0.1.1  swazm-VirtualBox

**Comment by tst-ccamp** [comment]
@swazm-zz This is a bit of an unusual check for the hostname. There's a ticket (#190) to clean it up. The issue could be caused by a capital letter in your hostname. The other thing to check is to run `hostname -a` and make sure that the first entry in your /etc/hosts file is that value. 

From the comment you just posted, I see that you do have capital letters in the hostname so you're hitting the bug that I pointed out. You can just go ahead and follow the suggestion to run the installer with the -hnmf flag.

**Comment by swazm-zz** [comment]
As you said the issue was caused by the capital letter and the punctuation in my hostname,
it works correctly
Thank you for your helps

**Comment by bradh** [comment]
If your problem is solved, can you close the ticket?
