### ISSUE TITLE
Automasking fails for images stored with UTM projection

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#254]
If an imagery resource is created from a source image that has a UTM projection set, Fusion will first convert the image to a different projection, then back again. This causes a double-border to appear around the image as a border is added each time the projection is changed. This will confuse the automasking operation, which will then only remove part of the border.

**Comment by tst-ccamp** [comment]
I'll work on creating a sample image that causes this issue.

**Comment by tst-lsavoie** [comment]
This also happens with NAD 1983 images.

**Comment by tst-lsavoie** [comment]
On closer inspection, this is not because of the projection but is caused by the fact that the image has a nodata value that doesn't fit in the pixel type. For example, the image could use bytes for pixels but have a nodata value of -10000. When the nodata value is cast to the pixel type it results in the extra border around images that isn't masked off.
