### ISSUE TITLE
Validate KML in Cutter

### ISSUE THREAD

**Issue by avnishb** [google/earthenterprise#280]
It may be worth performing basic validation on the KML that's pasted by the user in the Cutter UI, and subsequently added in the glb.

A simple tool for doing so is:

$ xmllint -noout file.kml

If the response is non-empty, then a warning could be shown to the user that their KML may be invalid.

Alternatively, just check the <Polygon> element(s).

**Comment by tst-blaird** [comment]
I recently had a problem where some code was trying to parse the polygon.kml file from earth_enterprise/src/fusion/portableglobe/globes/tutorial_sf.glm.  The XML parser I was using refused to parse it because of the blank line preceding the <xml> element which is technically malformed XML.  I had to add extra code to remove leading whitespace from the document.

I would like to see this issue resolved so other code that reads the polygon.kml doesn't have to fix up the XML.

**Comment by tst-ccamp** [comment]
This can be done using Javascript only. Also, do not break existing XML snippet capability.

**Comment by restouffer** [comment]
There is already Javascript validation when pasting KML to define a region in Cutter. You can verify this by pasting any text that is not valid KML into text area and clicking **Use KML**. The page will display a popup message that reads:

> **Invalid KML**
> Please confirm that you have entered valid KML.

**Comment by restouffer** [comment]
I created PR #1364 to explore implementing similar checks on the server.

**Comment by tst-blaird** [comment]
@restouffer  I do see that some validation is done.  I don't know how thorough it is but it does not prevent a blank line before the <?xml> declaration.  Maybe just removing leading whitespace from the pasted string is all that's needed?

**Comment by restouffer** [comment]
lxml will reject XML that starts with whitespace, so #1364 should prevent globes with bad KML from being built. It would be simple to trim whitespace from the KML in Javascript before it is saved, if that is a common scenario.

**Comment by tst-rwildes** [comment]
How hard would it be to add an XML schema check using the KML schema: http://schemas.opengis.net/kml/
Most XML parsers have this feature.

**Comment by tst-lsavoie** [comment]
Closed via PR #1364
