### ISSUE TITLE
Question Data base oracle or Postgres/postgis 

### ISSUE THREAD

**Issue by swazm-zz** [google/earthenterprise#298]
hi, 

How can we link GEE to an oracle or postgres database ??

thank you

**Comment by bradh** [comment]
@swazm-zz What are you trying to achieve with such a linkage - a POI search, or something else? Can you try to explain the use case and what you've already tried?

**Comment by swazm-zz** [comment]
I already have an oracle database, my project is to migrate to a postgres / postgis database and my goal is to automate the process of updating my database.
In a simple way if I update my database (Oracle or Postgres), it will be automatically updated on GEE.
Is there a script that allows us to do it ?
Thank you for your help

**Comment by bradh** [comment]
What is the relationship between your database and GEE? Are you expecting POI search, or some kind of raster data, or vector data? Are you trying to update a resource in fusion, or do something directly to the globe in the server? I still don't get what you are trying to achieve because I have no idea what is in your database or how that relates to your published globe.

Are you perhaps expecting GEE to be like the way GeoServer works with a postgis data store?

**Comment by swazm-zz** [comment]
Are you perhaps expecting GEE to be like the way GeoServer works with a postgis data store?
the answer is yes.
What I want to know if GEE can run or work as a regular Web GIS
The data is stored on postgres / postgis and updated via a heavy client (ArcGIS or QGIS) after that pushed too Geoserver and publish to client. ?

**Comment by bradh** [comment]
GEE and GeoServer are not that similar. GEE can serve from a built / published globe, and it supports special search plugins (e.g. for POI), but you can't (for example) dynamically render a WMS from features stored in the database.

You could build a new globe from the database content via fusion (or command line equivalents), but I don't believe there is any way to go direct from database to modified server behaviour without a new globe; unless all you want is simple search.

A hybrid solution would also be possible: you could use WMS from GEE and KML from GeoServer and blend those at the client, for example.

IMO, questions like this would be better asked on the slack channel. However I hope I've answered your concerns sufficiently.

**Comment by swazm-zz** [comment]
Thank you for your answer .

If I understand correctly, we can not upload a database (postgres/postgis) directly to fusion and we can not have a real time data into GEE

**Comment by swazm-zz** [comment]
I have another questions, is it possible to use GEE via just command line without GUI (centOS 7). My development and production machine are under CentOS 7 but without GUI ??

**Comment by tst-ppenev** [comment]
Are you asking if you could build and publish globes and maps from the command-line, as you can from Fusion? Fusion is just a UI for a number of command-line tools, which you could certainly use from the command-line if you know what commands to run. You could also look at the command logs when building a resource, a project, or a database in Fusion to see that commands that were run, which may help you.

If you are asking whether you can use GEE from the command line, I'm not sure how you would be trying to use it. GEE serves globe and map tiles, which you could certainly request from the command line, rather than a browser, or a desktop client. However, knowing what tiles exist, and constructing their URLs will take some work.

**Comment by avnishb** [comment]
Just FYI, Fusion does not directly integrate with Oracle; however, client integrations are possible via GeoServer:

http://www.oracle.com/technetwork/articles/lokitz-spatial-geoserver-087760.html

It's also feasible to build GDAL/OGR with support for Oracle Spatial:

http://www.gdal.org/drv_oci.html

**Comment by bradh** [comment]
@swazm-zz Does this answer your question? If you have more questions like this, remember the slack channel (see link button on main page) too.

**Comment by swazm-zz** [comment]
Yes, thank you very much 
Can you give me the link to the slack channel ( i can not find it ) ?

**Comment by bradh** [comment]
There is a button on https://github.com/google/earthenterprise that points to http://slack.opengee.org/

Can you close the ticket when you're satisfied with the response.

**Comment by swazm-zz** [comment]
ok thank you all
