### ISSUE TITLE
Update geconfigurepublishroot to fully correct file permissions

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#682]
If you are using a non-default publish root (e.g. /usr/local/google_test) then uninstall/reinstall GEE Server, and allow it to remove the geapacheuser and gegroup, it may use different uid values when recreating those users. (To simulate this problem, you can manually create the geapacheuser and gegroup, assigning different uid and gid, respectively, before reinstalling.)  You can use geconfigurepublishroot to reselect that path, which will update the but the ownership of the "search_space" and "stream_space" directories, but not the parent directory or any child directories/files. This ownership update should be done recursively. 

Note: it may not be appropriate to follow links when doing chown, and if it's decided that it links should be followed, then it's probably best to only chown if the files/directories are orphaned.

**Comment by MikeBiancalana** [comment]
This appears to already be fixed by cd812fb9a5daaa049c129631a17e8e65d45ea874, unless I'm missing something.

The current behavior is:
 * When uninstalling, ownership of publish root is recursively changed to root user and group, [here](https://github.com/google/earthenterprise/blob/d66b676c330e69a0496bad4b7c9f382baa9b3f1d/earth_enterprise/src/installer/uninstall_server.sh#L302)
 * When reinstalling, the selected publish root ownership is recursively changed to geapacheuser and gegroup, [here](https://github.com/google/earthenterprise/blob/d66b676c330e69a0496bad4b7c9f382baa9b3f1d/earth_enterprise/src/installer/install_server.sh#L513) (also as shown in the commit referenced above)

It is true that `geconfigurepublishroot` only changes ownership and permissions on the `search_space` and `stream_space` directories and not their contents, as stated in this issue. If there is a reinstall method or other likely scenario where that script is called and `install_server.sh` is not, then this issue will still be a problem. Otherwise, it seems to be fixed already.

**Comment by MikeBiancalana** [comment]
Created pull request just in case I did miss something.

**Comment by tst-ccamp** [comment]
Fixed in #749
