### ISSUE TITLE
Determine a method for doing Google Analytics on Jekyll yaml-based pages in opengee.org

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#772]
Files such as [index.html](https://github.com/google/earthenterprise/blob/5.2.1-6.final/docs/index.html) are written using yaml for use in GitHub Pages. However, since there is no <head> section, like the HTML files, it's not clear how to add the Google Analytics tag needed to track statistics.

### AC
1. Determine a method for adding Google Analytics to these pages in opengee.org
1. Update files as necessary

**Comment by JohnSell620** [comment]
It seems from #577 that Google Analytics was previously implemented but then altered when https://github.com/google/earthenterprise/pull/577/commits/2361567a4fd9b8e5645a460e886a302857e069bd was merged with google:master. Then the commit from Nov 1, 2017, https://github.com/tst-mswartz/earthenterprise/commit/8d1e1fd9d1c30c26d41fa9fdc48127ea06daa614, added code for Google Tag Manager (without Google Analytics tags), but has not been merged.

I was curious as to why the initial installation of Google Analytics was removed. Is this issue unresolved because of the problem described in #577 regarding the need to manually change the tracking ID in order to test on the master or fork? Otherwise, this seems like a simple fix. Thank you.
