### ISSUE TITLE
build error. ImportError: No module named khEnvironment

### ISSUE THREAD

**Issue by samyuchao** [google/earthenterprise#864]
when I Build Earth Enterprise Fusion and Server: scons -j8 release=1 build
I got the following message: 

scons: Reading SConscript files ...
ImportError: No module named khEnvironment:
  File "/home/itasca/earthenterprise/earth_enterprise/SConstruct", line 25:
    from khEnvironment import khEnvironment

**Comment by tst-lsavoie** [comment]
What directory are you in when you run the scons command?

**Comment by samyuchao** [comment]
It seems it failed to download some librarys.  It works after I download all again.

**Comment by tst-lsavoie** [comment]
Glad you got it working. Thanks for the update.

**Comment by david-lag** [comment]
Hello, I have already tried this, but I still have the same error:

scons: Reading SConscript files ...
ImportError: No module named khEnvironment:
  File "/home/price/earthenterprise/earth_enterprise/SConstruct", line 28:
    from khEnvironment import khEnvironment


executing the following command: 
scons -j8 release=1 build


on this route:
cd earthenterprise/earth_enterprise


### what is described in point number 4 of the following league
https://github.com/google/earthenterprise/blob/master/earth_enterprise/BUILD.md


HELP PLEASE  

*********I'M A NEWBIE*******

**Comment by tst-lsavoie** [comment]
@david-lag it's OK, newbies are welcome here.

Try running `git lfs pull` and then `scons -j8 release=1 build` again.

**Comment by david-lag** [comment]
hello thank you very much I have solved the eror returning to clone the league @tst-lsavoie 

however I have this error when compiling: scons -j8 release = 1 build
it loads several elements and in a moment it interrupts the load of files by this error:
make[1]: Leaving directory `/home/price/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/src'
make: *** [sub-src] Error 2
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/qt/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.

someone could help me please I am a new student of ing electronica thank you very much.

**Comment by tst-lsavoie** [comment]
Run the build again but use `scons -j1 release=1 build` and then post the error. That will make it easier for us to figure out.

**Comment by david-lag** [comment]
@ubuntu14:~/earthenterprise/earth_enterprise$ scons -j8 release = 1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** Do not know how to make File target `release' (/home/price/earthenterprise/earth_enterprise/release).  Stop.
scons: building terminated because of errors.

**Comment by david-lag** [comment]
Thanks for the support  @tst-lsavoie

**Comment by tst-lsavoie** [comment]
You need to take out the spaces in `release = 1`. It has to be `release=1` (no spaces).

**Comment by david-lag** [comment]
hahaha what great! if it's served something, it does not make me the same mistake, you're a crack

but something similar:

@ubuntu14:~/earthenterprise/earth_enterprise$ scons -j8 releas=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 releas=1 third_party
scons: Reading SConscript files ...
Unrecognized option: 'releas'
scons: *** [build] Error 1
scons: building terminated because of errors.

**Comment by david-lag** [comment]
@tst-lsavoie  I miss your headquarters the following: compile scons -j8 release=1 build  
and it does not throw me the previous error if it is not:

make[3]: Leaving directory `/home/price/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/tools/designer/designer'
make[2]: *** [sub-designer] Error 2
make[2]: Leaving directory `/home/price/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/tools/designer'
make[1]: *** [sub-designer] Error 2
make[1]: Leaving directory `/home/price/earthenterprise/earth_enterprise/src/NATIVE-REL-x86_64/third_party/qt/qt-x11-free-3.3.8b/tools'
make: *** [sub-tools] Error 2
scons: *** Error 2
scons: *** [NATIVE-REL-x86_64/third_party/qt/.build] Error 2
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.

**Comment by tst-lsavoie** [comment]
Can you post more of the output? This doesn't include the full error message.

**Comment by david-lag** [comment]
for 14 minutes run the command scons -j8 release=1 build and keep compiling :/  @tst-lsavoie

**Comment by david-lag** [comment]
just finished, it's too much output and I get the same error:

**Comment by tst-lsavoie** [comment]
I'll need more of the output to be able to figure out what's going on. Can you run it again but with `-j1` instead of `-j8` and post a few more lines than what you've posted so far?

**Comment by david-lag** [comment]
is all that comes out when executing the mentioned command:

@ubuntu14:~/earthenterprise/earth_enterprise$ scons -j1 releas=1 build
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j1 releas=1 third_party
scons: Reading SConscript files ...
Unrecognized option: 'releas'
scons: *** [build] Error 1
scons: building terminated because of errors.

**Comment by tst-lsavoie** [comment]
That's a spelling error. The command should be `scons -j1 release=1 build`

**Comment by david-lag** [comment]
@tst-lsavoie  right away it's loading

**Comment by david-lag** [comment]
[notas.txt](https://github.com/google/earthenterprise/files/3311700/notas.txt)




@tst-lsavoie  **thank you**

**Comment by tst-lsavoie** [comment]
As far as I can tell, this is your issue:
```
virtual memory exhausted: Cannot allocate memory
```
It looks like you're running out of memory. How much memory does your system have?

**Comment by tst-lsavoie** [comment]
You can check that by posting the output of `free -mh`.

**Comment by david-lag** [comment]
excellent that I was looking for thank you very much, wait @tst-lsavoie

**Comment by david-lag** [comment]
hahahahahaha Great !!!!!!! I am totally grateful, I will mount another virtual machine with more resources, thank you very much indeed, my most cordial greetings I hope to have that level (and) and congratulations, see you, until the next mistake hahaha thanks! @tst-lsavoie

**Comment by david-lag** [comment]
Everything has gone great, thank you very much, now I only have one question, after everything has worked correctly, how can I get the product?

Where do I visualize and how?  @tst-lsavoie

**Comment by david-lag** [comment]
prise@ubuntu14:~/earthenterprise/earth_enterprise/src$ fusion
fusion: cannot connect to X server

Is the graphical environment bad? @tst-lsavoie

**Comment by tst-lsavoie** [comment]
It does look like something is wrong with your graphical environment. I would look up how to install X server on your Linux distribution.

As far as getting data, the idea behind Open GEE is that we provide the software and you use your own imagery. We do have some tutorial imagery and some links to places where you can get data (https://github.com/google/earthenterprise/wiki/Shared-GEE-Assets).

I would highly recommend going through the Fusion tutorial (http://www.opengee.org/geedocs/5.3.1/answer/4412440.html). You will understand much better how Fusion works and you'll get access to some sample imagery.

Finally, I won't be available much to answer questions the next little while. There are lots of others that can help, though. You can also use our Slack channel, which is linked from our main page.
