### ISSUE TITLE
Default sourcedate for terrain / imagery import command doesn't work

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#92]
Shown by:
```
genewimageryresource --nomask -o Resources/Imagery/BlueMarbleBathy /gevol/src/prebuilt/BlueMarbleBathy/BlueMarbleBathy.kip
Fusion Warning: Can't parse date/time: 0000-00-00
```

Basically the --sourcedate option isn't optional at the moment.

**Comment by bradh** [comment]
initial analysis shows that the glibc `strptime` will fail for that date/time, and that is the underlying error.

**Comment by tst-ccamp** [comment]
@bradh It does accept it if it's passed as a parameter, though, right?

**Comment by bradh** [comment]
The commands are OK if you pass a valid parameter value:
`genewimageryresource --sourcedate 2004-07-01 ...` works fine
but
`genewimageryresource --sourcedate 2004-07-00 ...` fails.

Currently thinking of changing the default value (at the `commons/khDefine.cpp` level) to something old-but-valid (`0000-01-01`)

**Comment by bradh** [comment]
Went with a different parsing approach, rather than redefine the constant.

**Comment by andreisel** [comment]
@tst-ccamp, @tst-lsavoie , @bradh 

If date is not specified, it should be set to unknown by default (see, [jpeg_comment_date.cc](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/keyhole/jpeg_comment_date.cc#L81))

That warning seems being raised in  `bool TimeToHexString()` [here](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/common/khStringUtils.cpp#L286), and I believe it happens when parsing time in [serverdbReader.cpp](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/common/serverdb/serverdbReader.cpp#L184)

Please see
[TimeToHexString](https://github.com/google/earthenterprise/blob/master/earth_enterprise/src/common/khStringUtils.cpp#L286)

The solution could be modifying TimeToHexString to return default date_time in case of parsing error. Also, maybe drop the bool-return.

void TimeToHexString(const std::string& input,
                     std::string* date_time_hex,
                     std::string* date_hex,
                     std::string* time_hex) {
  // Assume input is in UTC format.
  struct tm time = {0};
  if (!ParseUTCTime(input, &time)) {
    keyhole::JpegCommentDate jpeg_date;
    std::string date_hex_ = jpeg_date.GetHexString();
    date_time_hex = date_hex_;
    if (date_hex) {
      *date_hex = date_hex_;
    }
    return;
  }

  // Build date hex code in case of date-time string successfully parsed.
  keyhole::JpegCommentDate::YearMonthDayKey jpeg_date_key;
  keyhole::JpegCommentDate::YearMonthDayKeyFromInts(
      time.tm_year + 1900, time.tm_mon + 1, time.tm_mday, &jpeg_date_key);
  keyhole::JpegCommentDate jpeg_date(jpeg_date_key);
  std::string date_hex_ = jpeg_date.GetHexString();
  ...
}


#179  
I believe when creating an asset with either the Asset Manager or  the `genewimageryresource- tool`, we have to get 0000-00-00 date when it is not specified/set.

**Comment by bradh** [comment]
I came up with a different approach that avoids changing the internal parsing (where we `strptime()`), and just passes through a fixed string.
