### ISSUE TITLE
Create "Known issues" section

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#93]
Should go on one or more:

1. README
1. Wiki

Take a look at the issues list and add info to the section. Include work-arounds if they exist

**Comment by tst-ahernandez** [comment]
Wiki page created with links back to each issue!
https://github.com/google/earthenterprise/wiki/Known-Issues

I was thinking about the README but I have an alternative solution to that. I think the known issues list would be good to package into a release whenever we hit a release. We could create a new file in the main repo directory (known_issues.md) when we are at that point so that we can publish each version with the list of known issues.

Other than that, I'll keep updating the known issues list every Friday as issues go come in and out of the repo.

**Comment by tst-ccamp** [comment]
@tst-ahernandez For now, you might just update the README with a link to the Wiki. And when we create a release, we can move that to the known_issues.md file.

**Comment by tst-ahernandez** [comment]
Added link to the known issues page in the README.
@tst-ccamp This should be good to go.

**Comment by tst-ccamp** [comment]
Hey, @tst-ahernandez I think some of the issues you have listed there are actually feature enhancements. They probably don't have to be on the page. Do you want me to go through and weed out the ones I don't think should be listed?

**Comment by tst-ahernandez** [comment]
@tst-ccamp Just updated the page with the enhancements removed. Good catch!

**Comment by tst-ccamp** [comment]
One more thing. I don't think we should include issues on the page if we can't verify them as bugs, such as:  https://github.com/google/earthenterprise/issues/96, https://github.com/google/earthenterprise/issues/65, etc.

**Comment by tst-ahernandez** [comment]
Okay, so only issues that are bugs?

**Comment by tst-ccamp** [comment]
Yeah, we don't want to include too much stuff otherwise people could just look at the issues :) Later on we might want to include some workarounds where they exist too.

**Comment by tst-ahernandez** [comment]
Alright, give it a gander now.

**Comment by tst-ahernandez** [comment]
This has been merged! Closing
