### ISSUE TITLE
Portable server builds require file generated by geserver build

### ISSUE THREAD

**Issue by tst-jhaight** [google/earthenterprise#973]
The portable server build is looking for `earth_enterprise/src/version.txt` and fails because it is not generated without the full earthenterprise build.  As a consequence of this, portable server cannot be built for windows without some manual steps to create that file and put it in the correct location.

AC:

1. Portable server builds are independent of regular geserver/gefusion builds.

**Comment by tst-ppenev** [comment]
SCons should run on Windows?  Did you have trouble generating `version.txt`?

We would need to add more installation instructions.

**Comment by tst-jhaight** [comment]
I didn't attempt to run a scons build since I didn't expect it to succeed and didn't want to install a bunch of tools I didn't really need.  Is there a scons target that would only generate version.txt?

I filed this since building the release_5.2.3 branch I didn't have problems with version.txt.

**Comment by tst-ppenev** [comment]
The target is the path to the file you want to generate.  E.g., something like:

```bash
scons src/NATIVE-REL-x86_64/gee_long_version.txt
```

**Comment by tst-rwildes** [comment]
Running `scons` from `earth_enterprise` folder with no parameters does generate the `version.txt` file without having to do a full open build but not in Windows.  The scons script fails under Windows which is another issue IMO.  A work around under Windows (version 10) is to run the `scons` command from within a `bash` window with no parameters.  This will then create the file and you can switch back to a windows command prompt to do the rest.  If you are in a Windows command prompt and have bash for Windows installed you can just execute `bash` to jump into a bash shell then execute `scons` then `exit` to get back to Windows command prompt.

**Comment by tst-rwildes** [comment]
I want to correct myself.  Both I and @tst-ppenev made incorrect statements on how to get scons to generate the version.txt file...  As is right now to get the file to generate you have to cd into `earth_enterprise/src` and from within that directory you can run `scons NATIVE-DBG-x86_64/gee_version.txt` to get scons to generate the needed version.txt file. 

This has a couple of issues: 
- this requires scons and if we are going to require scons to build portable we should open another issue to just add the portable builds to the scons build system.  I do feel that should be a different issue and not addressed with this issue but I thought I'd mention it.
- the bigger issue is that running that command is unintuitive and we should have an easier command to run.  This may be addressed with the fix for #984. 
- we need to update the documentation or maybe the current build scripts (assuming the first point isn't addressed right away) to run the scons command to generate the version file.

**Comment by tst-ppenev** [comment]
Yes, thanks for the correction @tst-rwildes.

I think it would be better to avoid requiring `scons` to build Portable on Windows.  Since the version code is all in Python, and the Portable build is a pure Python script, we may be able to just put that code into a module that can be reused from `scons` and from the Portable build.

**Comment by tst-rwildes** [comment]
@tst-ppenev it looks like #1029 PR that @tst-kfreiheit has pulls the logic out of scons and into a python script.  That change will be a good step in the right direction for a solution to this issue.

**Comment by tst-ppenev** [comment]
@tst-rwildes, yes, I think it would help.  I only wish the calculation of the `version_file` was not in the `main()` function, so you could use it from other Python modules without having to set a command line.

Grumble, grumble.

**Comment by tst-rwildes** [comment]
@tst-ppenev it actually works both ways.  If you look at the scons code it consumes the shared code via an import and calls the methods directly (no need to use it via command line).  Since the portable build scripts are written in Python they should be able to do the same thing.  I think the command line currently is used for testing (but could be used for other things too).

**Comment by tst-ppenev** [comment]
Yes, I saw how it works, and I might have suggested making that a Python module that can be re-used.

But the `backupFile` is not only for testing.  It's intention was for being able to build from a clone that doesn't have the whole Git history.  The `src/SConstruct` has the path to the 'backup' `version.txt` file, and any other caller of the `GetVersion` and `GetLongVersion` functions needs to know that path, as well.
